import { GoogleGenerativeAI } from "@google/generative-ai";
import { config } from "../../shared/config.js";

/**
 * Generates an analysis using the Google Gemini API.
 *
 * @async
 * @function generateAnalysis
 * @param {string} prompt - Prompt with the model data (in Spanish by design).
 * @returns {Promise<string>} Text of the response generated by the model.
 * @throws {Error} If the API key is not configured or the call fails.
 * @example
 * const analysis = await generateAnalysis(prompt);
 */
export async function generateAnalysis(prompt) {
  if (!config.geminiApiKey) {
    throw new Error("GEMINI_API_KEY is not configured in the environment.");
  }

  const genAI = new GoogleGenerativeAI(config.geminiApiKey);
  const model = genAI.getGenerativeModel({ model: config.geminiModel });

  const result = await model.generateContent(prompt);
  return result.response.text();
}
