import OpenAI from "openai";
import { config } from "../../shared/config.js";

/**
 * Generates an analysis using the OpenRouter API (compatible with the
 * OpenAI SDK). The provider and the model are read from the global config.
 *
 * @async
 * @function generateAnalysis
 * @param {string} prompt - Prompt with the model data (in Spanish by design).
 * @returns {Promise<string>} Text of the response generated by the model.
 * @throws {Error} If the API key is not configured or the call fails.
 * @example
 * const analysis = await generateAnalysis(prompt);
 */
export async function generateAnalysis(prompt) {
  if (!config.openRouterApiKey) {
    throw new Error("OPENROUTER_API_KEY is not configured in the environment.");
  }

  const client = new OpenAI({
    baseURL: config.openRouterBaseUrl,
    apiKey: config.openRouterApiKey,
    defaultHeaders: {
      "HTTP-Referer": "https://github.com/artificial-analysis-tool",
      "X-Title": "Artificial Analysis Tool",
    },
  });

  const completion = await client.chat.completions.create({
    model: config.openRouterModel,
    messages: [{ role: "user", content: prompt }],
  });

  return completion.choices[0]?.message?.content ?? "";
}
